#!/bin/bash

# Publishes the open sourceable code to github
# Author: brett

SC_FILE="./.git/info/sparse-checkout"
git config core.sparsecheckout true

cp ./sparse-checkout $SC_FILE
git read-tree -mu HEAD

rsync -av --progress . ../publishmystuff --exclude .git

rm ../publishmystuff/snapshot-to-github
rm ../publishmystuff/sparse-checkout

echo "*" > $SC_FILE
git config core.sparsecheckout true
git read-tree --reset -u HEAD

rm $SC_FILE
git config core.sparsecheckout false
